### ISSUE TITLE
Maybe Chiadog gets in the way of chia-blockchain synchronization

### ISSUE THREAD

**Issue by BaraoVlask** [martomi/chiadog#153]
I'm not sure, because I don't know much about blockchain and pythom but every time I start using the chia dog I start to have problems with synchronization with the blockchain, it could be just me or some configuration that I did wrong but I couldn't fail to notice the pattern, it may be a coincidence but if someone can explain, it would be great

**Comment by Zanooda** [comment]
Chiadog should not interfere with your client synchronization since it is only reading the debug logging output.
Though if you are running your Chia daemon on minimal hardware (Raspberry Pi) your system might already be bottlenecked by CPU, memory or IO and you most probably will encounter synchronization issues even without Chiadog in near future when the number of transactions and the blockchain size increases.

**Comment by djdookie** [comment]
I am running both on a Pi4 and I never get desynced. Try installing the newest chia client 1.1.6 which was released today.
It fixes a lot of performance and syncing problems.

The frequency of transactions should not rise, but the blockchain size will. But I doubt it is an additional performance problem in the future.

**Comment by BaraoVlask** [comment]
tanks for the help
