### ISSUE TITLE
Error when running remote windows harvester

### ISSUE THREAD

**Issue by BubbleTrouble14** [martomi/chiadog#208]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/farmer/chia-watchdog/chiadog/src/chia_log/log_consumer.py", line 152, in _consume_loop
    if self._has_rotated(self._remote_log_path):
  File "/home/farmer/chia-watchdog/chiadog/src/chia_log/log_consumer.py", line 172, in _has_rotated
    self._log_size = int(stdout.readline())
ValueError: invalid literal for int() with base 10: ''

**Comment by pieterhelsen** [comment]
Do you get this error immediately on startup or when the file rotates?

**Comment by pieterhelsen** [comment]
It looks like Windows isn't finding your config file and as such returns an empty string trying to read the log size. 
That's why it's important to know whether it occurs at startup (your config file is likely misconfigured) or during operations (the log file is rotated in such a way that the file is not available - likely just for a split second)

**Comment by BubbleTrouble14** [comment]
Okay, ill have a look again. But was 100 percent sure it was setup correctly.

**Comment by pieterhelsen** [comment]
Can you adjust the `log_level` in the Chiadog config to `DEBUG` and report back with your full config (make sure to remove any usernames/passwords) and the output from the Chiadog stdout log?

**Comment by mezzovide** [comment]
Hi, this is the problem
https://github.com/martomi/chiadog/pull/216#issue-659175062
Tested and PR made
