### ISSUE TITLE
pygtail is not in venv

### ISSUE THREAD

**Issue by ojura** [martomi/chiadog#212]
**Describe the bug**

When running start.sh, I get:
ModuleNotFoundError: No module named 'pygtail'
Tested at 429b90c

**Environment:**
 - OS:  Ubuntu 20.04
 - Python version: 3.8 (Ubuntu stock)
 - PIP version: 20.0.2
 - Chia version: unrelated

**Comment by pieterhelsen** [comment]
Did you run `install.sh` after you updated to the new version?

**Comment by ojura** [comment]
Ah, I haven't. But I tried `pip3 install pygtail` and it still wouldn't find it, presumably because it was installed into .local and not into the venv.

Perhaps notify users that they need to run install.sh? I easily missed it, especially since I was able to run it before without that.

**Comment by pieterhelsen** [comment]
I would indeed expect that it is due to the installation to local instead of venv. Were you able to resolve the issue running `install.sh`?

The `install.sh` procedure is mentioned the upgrade instructions [here](https://github.com/martomi/chiadog#updating-to-the-latest-release). How can improve further on the documentation?

**Comment by ojura** [comment]
Yes, it has of course fixed the problem, and the documentation is adequate. However, the problem was that I haven't looked at the documentation :) My suggestion was something like printing a reminder to the user to run `install.sh` if they skipped looking at the docs like I did.
