### ISSUE TITLE
Finished but out-of-order signage points (SPs) are incorrectly reported as skipped

### ISSUE THREAD

**Issue by ems1985** [martomi/chiadog#311]
**Describe the bug**

Due to increased stress on systems caused by the recent "dust storm" (read more here: https://github.com/Chia-Network/chia-blockchain/discussions/9049) it can happen that signage points (SPs) are cached and then finished out of order. It seems when SPs are out of order chiadog thinks that the SPs were skipped, even though they are finished a few seconds later.

This screenshot shows the skipped SP warning plus the log for the warning time showing the out-of-order SPs:
<img width="1981" alt="Screenshot 2021-10-31 at 23 06 50" src="https://user-images.githubusercontent.com/34405275/139603105-5d0ad399-0ef7-4359-af03-c21b83d3eac4.png">

Here is a log from the chat discussing this possible issue:
<img width="702" alt="Screenshot 2021-10-31 at 23 23 48" src="https://user-images.githubusercontent.com/34405275/139603133-c1478322-7087-4516-811d-66f078dad939.png">

**Environment:**
 - OS: Ubuntu Server
 - Python version: 3.8.10
 - PIP version: pip 21.3.1
 - Chia version: 1.2.10
 - Chiadog version: 0.7.0
 - Harvester: local

**Comment by martomi** [comment]
We have a test for out-of-order signage points here: https://github.com/martomi/chiadog/blob/main/tests/chia_log/logs/finished_signage_point/scrambled.txt

Seems that doesn't cover current events on the network. I may look into this but since I don't have access to running node at the moment, someone needs to prepare and upload a text file with example sequence that fails the test as the linked above example. [This format](https://github.com/martomi/chiadog/blob/main/tests/chia_log/logs/finished_signage_point/nominal.txt) also works. Then I can look into it.

If someone else wants to look into it, please start by adding a test here that fails and we can start working on a fix: https://github.com/martomi/chiadog/blob/main/tests/chia_log/handlers/test_finished_signage_point_handler.py

**Comment by ems1985** [comment]
Unfortunately all I have is this screenshot above. Don't have the old log files anymore and I didn't get the skipped SPs message anymore since the dust storm appears to be over...

**Comment by martomi** [comment]
Closing due to lack of additional actionable information.
