### ISSUE TITLE
chiadog not working with database v-2

### ISSUE THREAD

**Issue by chia-farmer** [martomi/chiadog#334]
**After updating chia to version 1.3.x with database v_2, chiadog cannot read plots. (shows 0 plots) Tested in win 10 and Ubuntu**

A clear and concise description of what the bug is and how it can be reproduced.

**Environment:**
 - OS: win10 & Ubuntu
 - Python version: 3.8
 - PIP version: 
 - Chia version: 1.3.3
 - Chiadog version: 0.7.0-1
 - Harvester: remote OR local local

**Comment by pieterhelsen** [comment]
Did you completely reinstall Chia? It might be that your Chia config file logging reverted back to WARNING instead of INFO. 
I have been running Chiadog on 1.3.X for a couple of weeks and have had zero issues. Updated to 1.3.3 yesterday and again, no issues. This is on Ubuntu, using both local and remote harvesters.

**Comment by chia-farmer** [comment]
Yes indeed. The config file was updated and contained a warning. Thanks!
