### ISSUE TITLE
Don't let dev be the new main

### ISSUE THREAD

**Issue by gumba4** [martomi/chiadog#39]
Thanks for chiadog, it's replaced my own scripts. I suggest to not fall into the "dev branch trap".
We have seen at plotman what happens when the main branch is not maintained and progress only happens on dev (users have to maintain own forks, difficult to update once it is eventually merged etc.).
The chia team decided to get rid of the dev branch altogether, a good choice imo. Instead they develop features on separate branches and merge them via pull requests into main.
If you have confirmed features are working, please consider integrating them into main sooner than later.

**Comment by martomi** [comment]
Thanks for your concern, I'm aware of this fallacy. 

So far there has not been a feature sitting dormant in `dev` for longer than a week so I don't see it being a problem.

Features are already being developed in separate feature branches and tested prior to merging to `dev`. So if you want to stay on the bleeding edge, you can run from that branch. The difference is < 7 days.

`main` is meant to be a stable branch that is aligned with releases and has a slower release cadence of once a week at most (unless hotfixes are necessary). It allows for features to have been tested for a few days before release and reduces the overhead that people need to go through in order to stay up-to-date. I.e. less frequent need to familiarise with new features and audit changes to the codebase.

That being said, the next release was [already prepared](https://github.com/martomi/chiadog/pull/37) yesterday. But last minute I've noticed that newest version of Chia removed the logs for added coins, and that presents a small setback.

**Comment by gumba4** [comment]
Thanks! That's good to hear.
