### ISSUE TITLE
Notify harvest timeout

### ISSUE THREAD

**Issue by cattivik66** [martomi/chiadog#49]
Based on https://chiaforum.com/t/troubleshooting-failure-to-farm-with-lots-of-plots-due-to-harvester-30s-timeout/413/3 and https://github.com/Chia-Network/chia-blockchain/issues/2651 , it seems there could be some troubles if, for any reason, the harvester takes too much time to reply.

`2021-04-24T16:03:29.433 harvester chia.harvester.harvester: INFO     3 plots were eligible for farming 1c75d8d21c... Found 0 proofs. Time: 7.92976 s. Total 522 plots`

The Time should be, usually, under 5 seconds. So in this example it would be nice to get a notification.
It this time is going around 15 seconds there is the risk to miss the rewards.
If it is 30 seconds than matematically any possible reward is lost, even if there were some eligible.

**Comment by martomi** [comment]
There [is already a check](https://github.com/martomi/chiadog/blob/main/src/chia_log/handlers/condition_checkers/quick_plot_search_time.py) for that. You can also see it in the example notifications in the README. 

The daily stats are also calculating [the average time to respond](https://github.com/martomi/chiadog/blob/main/src/chia_log/handlers/daily_stats/stat_accumulators/search_time_stats.py).

Anyone is welcome to open a PR that also calculated the number of responses > 5 seconds. Alert notifications are currently sent for anything over 20 seconds because that's already risky late.

**Comment by martomi** [comment]
Thanks @cattivik66 for the suggestions, I've added a statistic for number of occasions > 5 seconds search times happen during the day.

**Comment by martomi** [comment]
Example of the new daily summary about search times:

![paste](https://user-images.githubusercontent.com/3739458/116320220-20244100-a7b8-11eb-89e4-2e5a087fa90a.png)
